{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Advance Python Assignment -8**\n",
    "\n",
    "**KUNAL SINGH**\n",
    "\n",
    "**Q1. What are the two latest user-defined exception constraints in\n",
    "Python 3.X?**\n",
    "\n",
    "The two latest user defined exception constraints in Python 3 are:\n",
    "\n",
    "1.  **The \\_\\_str\\_\\_ method**\n",
    "\n",
    "The \\_\\_str\\_\\_ method is used to convert an object into a string. This\n",
    "is useful for debugging and logging purposes. The \\_\\_str\\_\\_ method\n",
    "should always be defined for user-defined exceptions.\n",
    "\n",
    "**2. The \\_\\_repr\\_\\_ method**\n",
    "\n",
    "The \\_\\_repr\\_\\_ method is used to represent an object in a way that can\n",
    "be evaluated by Python. This is useful for debugging and introspection\n",
    "purposes. The \\_\\_repr\\_\\_ method should always be defined for\n",
    "user-defined exceptions.\n",
    "\n",
    "**Q2. How are class-based exceptions that have been raised matched to\n",
    "handlers?**\n",
    "\n",
    "In Python, class-based exceptions that have been raised are matched to\n",
    "handlers using a mechanism known as exception handling or exception\n",
    "propagation. This process involves the interpreter searching for the\n",
    "appropriate exception handler in the call stack.\n",
    "\n",
    "Here's how it works:\n",
    "\n",
    "1.  **Raising an Exception**: When an exception is raised within your\n",
    "    > code, either by using the raise statement or as a result of an\n",
    "    > error condition (e.g., division by zero), Python creates an\n",
    "    > exception object that carries information about the exception,\n",
    "    > including its type (which is typically a class representing the\n",
    "    > exception) and any associated data or messages.\n",
    "\n",
    "2.  **Propagation of the Exception**: Python starts looking for an\n",
    "    > appropriate exception handler for the raised exception. It does\n",
    "    > this by unwinding the call stack, which means it goes up the chain\n",
    "    > of function and method calls in reverse order to find a matching\n",
    "    > except block.\n",
    "\n",
    "3.  **Matching the Exception Type**: At each level of the call stack,\n",
    "    > Python checks the type of the raised exception against the types\n",
    "    > specified in except blocks. It looks for an except block with a\n",
    "    > matching exception type. If a match is found, the code inside that\n",
    "    > except block is executed.\n",
    "\n",
    "4.  **Handling the Exception**: Once a matching except block is found\n",
    "    > and executed, the exception is considered handled, and Python does\n",
    "    > not continue searching for more matching handlers. The code within\n",
    "    > the matching except block can handle the exception in various\n",
    "    > ways, such as logging the error, displaying an error message, or\n",
    "    > taking corrective action.\n",
    "\n",
    "5.  **Exception Propagation if Not Matched**: If Python reaches the top\n",
    "    > of the call stack (the global level) without finding a matching\n",
    "    > except block, the program will terminate, and an unhandled\n",
    "    > exception error message will be displayed. This means that\n",
    "    > unhandled exceptions typically result in program termination.\n",
    "\n",
    "**Q3. Describe two methods for attaching context information to\n",
    "exception artefacts.**\n",
    "\n",
    "There are two methods for attaching context information to exception\n",
    "artefacts in Python.\n",
    "\n",
    "1.  **Using the \\_\\_context\\_\\_ attribute**\n",
    "\n",
    "> The \\_\\_context\\_\\_ attribute can be used to attach a reference to\n",
    "> another exception to an exception object. This can be useful for\n",
    "> providing additional information about the context in which the\n",
    "> exception occurred. For example, the following code shows how to\n",
    "> attach the Valtry:\n",
    ">\n",
    "> raise ValueError(\"ValueError\")\n",
    ">\n",
    "> except TypeError as e:\n",
    ">\n",
    "> e.\\_\\_context\\_\\_ = ValueError(\"ValueError\")\n",
    ">\n",
    "> raise eueError exception to the TypeError exception:\n",
    "\n",
    "In this example, the ValueError exception is attached to the TypeError\n",
    "exception as its \\_\\_context\\_\\_ attribute. This means that the\n",
    "TypeError exception will now have a reference to the ValueError\n",
    "exception, which can be accessed using the \\_\\_context\\_\\_ attribute.\n",
    "\n",
    "> **2. Using the \\_\\_cause\\_\\_ attribute**\n",
    ">\n",
    "> The \\_\\_cause\\_\\_ attribute can be used to attach a reference to\n",
    "> another exception to an exception object. This can be useful for\n",
    "> providing information about the cause of the exception. For example,\n",
    "> the following code shows how to attach the ValueError exception to the\n",
    "> TypeError exception:\n",
    ">\n",
    "> try:\n",
    ">\n",
    "> raise ValueError(\"ValueError\")\n",
    ">\n",
    "> except TypeError as e:\n",
    ">\n",
    "> e.\\_\\_cause\\_\\_ = ValueError(\"ValueError\")\n",
    ">\n",
    "> raise e\n",
    "\n",
    "In this example, the ValueError exception is attached to the TypeError\n",
    "exception as its \\_\\_cause\\_\\_ attribute. This means that the TypeError\n",
    "exception will now have a reference to the ValueError exception, which\n",
    "can be accessed using the \\_\\_cause\\_\\_ attribute.\n",
    "\n",
    "The difference between the \\_\\_context\\_\\_ and \\_\\_cause\\_\\_ attributes\n",
    "is that the \\_\\_context\\_\\_ attribute can only reference other exception\n",
    "objects, while the \\_\\_cause\\_\\_ attribute can reference any object.\n",
    "This means that the \\_\\_cause\\_\\_ attribute can be used to attach more\n",
    "general context information to an exception object, such as a string\n",
    "message or a dictionary.\n",
    "\n",
    "Q4. Describe two methods for specifying the text of an exception\n",
    "object's error message.\n",
    "\n",
    "1.  **Using the \\_\\_init\\_\\_ method**\n",
    "\n",
    "The \\_\\_init\\_\\_ method can be used to specify the text of an exception\n",
    "object's error message when the exception object is created. The\n",
    "following code shows how to specify the text of an exception object's\n",
    "error message using the \\_\\_init\\_\\_ method:\n",
    "\n",
    "> class MyException(Exception):\n",
    ">\n",
    "> def \\_\\_init\\_\\_(self, message):\n",
    ">\n",
    "> super().\\_\\_init\\_\\_(message)\n",
    ">\n",
    "> try:\n",
    ">\n",
    "> raise MyException(\"This is an exception\")\n",
    ">\n",
    "> except MyException as e:\n",
    ">\n",
    "> print(e)\n",
    "\n",
    "In this example, the MyException exception object is created with the\n",
    "message argument set to \"This is an exception\". The \\_\\_init\\_\\_ method\n",
    "of the MyException class then uses this message to set the text of the\n",
    "exception object's error message.\n",
    "\n",
    "**2. Using the message attribute**\n",
    "\n",
    "The message attribute can be used to specify the text of an exception\n",
    "object's error message after the exception object has been created. The\n",
    "following code shows how to specify the text of an exception object's\n",
    "error message using the message attribute:\n",
    "\n",
    "> try:\n",
    ">\n",
    "> raise Exception(\"This is an exception\")\n",
    ">\n",
    "> except Exception as e:\n",
    ">\n",
    "> e.message = \"This is a new message\"\n",
    ">\n",
    "> print(e)\n",
    "\n",
    "In this example, the Exception exception object is created with the\n",
    "default error message. The message attribute of the exception object is\n",
    "then set to \"This is a new message\". The new message will then be\n",
    "displayed when the exception object's error message is printed.\n",
    "\n",
    "**Q5. Why do you no longer use string-based exceptions?**\n",
    "\n",
    "String based exceptions were used in Python 2.x. However, they were\n",
    "removed in Python 3.x because they had several limitations:\n",
    "\n",
    "-   They were not as flexible as exception classes.\n",
    "\n",
    "-   They could not be used to attach context information to the\n",
    "    > exception.\n",
    "\n",
    "-   They could not be used to chain exceptions.\n",
    "\n",
    "Exception classes are more flexible and powerful than string based\n",
    "exceptions. They can be used to attach context information to the\n",
    "exception, and they can be used to chain exceptions. This makes them\n",
    "more useful for debugging and handling errors.For these reasons, string\n",
    "based exceptions were removed in Python 3.x.\n",
    "\n",
    "**/ KUNAL SINGH**"
   ],
   "id": "42a14256-91c8-446e-92a7-ab6bf11055d3"
  }
 ],
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {}
}
